spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: auth-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  sql:
    init:
      mode: always
      platform: postgres

server:
  port: ${SERVER_PORT}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

user:
  service:
    url: ${USER_SERVICE_URL}

jwt:
  secret: ${JWT_SECRET}
  access-token:
    expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
  refresh-token:
    expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}

logging:
  level:
    com.internship.auth_service: DEBUG
    org.springframework.security: INFO