apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: internship
data:
  # Database URLs (for user-service, auth-service)
  DB_USERNAME: "postgres"
  
  # Redis
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  REDIS_DATABASE: "0"
  
  # Server ports
  SERVER_PORT: "8080"
  
  # Service URLs
  USER_SERVICE_URL: "http://user-service:8080"
  AUTH_SERVICE_URL: "http://auth-service:8081"
  
  # Service URLs for API Gateway
  SERVICES_AUTH_SERVICE: "http://auth-service:8081"
  SERVICES_USER_SERVICE: "http://user-service:8080"
  SERVICES_ORDER_SERVICE: "http://order-service:8082"
  SERVICES_PAYMENT_SERVICE: "http://payment-service:8084"
  
  # JWT
  JWT_ACCESS_TOKEN_EXPIRATION: "3600000"
  JWT_REFRESH_TOKEN_EXPIRATION: "2592000000"

