apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: internship
type: Opaque
stringData:
  DB_PASSWORD: "postgres"
  POSTGRES_PASSWORD: "postgres"
  REDIS_PASSWORD: ""
  JWT_SECRET: "mySuperSecretKeyForJWTGenerationThatIsAtLeast32BytesLong123!"

